### ISSUE TITLE
Python setup.py import numpy while having as dependency

### ISSUE THREAD

**Issue by matthew-jones-uk** [hobu/laz-perf#63]
In ```laz-perf/python/setup.py``` the numpy module is imported whilst also being an installation dependency. This means that if lazperf is in a dependency chain, such as a ```requirements.txt```, then the installation will fail. A possible solution would be to remove numpy from ```setup.py``` but this may not be easy in this use case. Looking at it briefly, would it be possible to move the setup() call to the top of the file so that numpy loads the dependency before the import?

In my situation I can reproduce by installing the module in a docker instance before numpy is installed. You should also be able to reproduce with a fresh virtualenv of Python installation.

This is the error that is produced in my situation:
```
  Downloading https://files.pythonhosted.org/packages/07/e9/2020d50b7c9465831f6246812c382b03cff14c5b4708b53cbebd1d2e61c1/lazperf-1.3.tar.gz (186kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-whuivcst/lazperf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-whuivcst/lazperf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-whuivcst/lazperf/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-whuivcst/lazperf/setup.py", line 11, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by hobu** [comment]
The setup.py needs numpy to get the `numpy.get_include()`, which it then uses to compile the interface with cython. I'm not sure how to resolve this circular dependency.

**Comment by matthew-jones-uk** [comment]
[This ](https://stackoverflow.com/questions/19919905/how-to-bootstrap-numpy-installation-in-setup-py/21621689)seems to be related, I'll try and take a look sometime if I have time.

**Comment by hobu** [comment]
@3b5f70e should fix this taking the approach you linked. Grab master and give it a try.

**Comment by matthew-jones-uk** [comment]
Issue seems to still exist, maybe that link no longer works.

This time testing on a fresh Python installation on Windows
```
Collecting lazperf
  Using cached https://files.pythonhosted.org/packages/07/e9/2020d50b7c9465831f6246812c382b03cff14c5b4708b53cbebd1d2e61c1/lazperf-1.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\User\AppData\Local\Temp\pip-install-c4nlnopu\lazperf\setup.py", line 11, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'

    ----------------------------------------
```

**Comment by hobu** [comment]
I didn't push a new release yet. You'll need to clone and grab master to test.

**Comment by matthew-jones-uk** [comment]
Yup, ran ```git clone https://github.com/hobu/laz-perf``` 
then ```pip3 install file:\\C:\Users\User\test\laz-perf\python lazperf```

**Comment by matthew-jones-uk** [comment]
Wait, my bad, accidentally installed lazperf along with it. Seems to have fixed it, it's now returning:
```
    Complete output from command "c:\program files\python37\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\User\\AppData\\Local\\Temp\\pip-req-build-1xp7tl_k\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\User\AppData\Local\Temp\pip-record-10x8zrc0\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\lazperf
    copying lazperf\__init__.py -> build\lib.win-amd64-3.7\lazperf
    running egg_info
    creating lazperf.egg-info
    writing lazperf.egg-info\PKG-INFO
    writing dependency_links to lazperf.egg-info\dependency_links.txt
    writing top-level names to lazperf.egg-info\top_level.txt
    writing manifest file 'lazperf.egg-info\SOURCES.txt'
    reading manifest file 'lazperf.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*' under directory 'laz-perf'
    writing manifest file 'lazperf.egg-info\SOURCES.txt'
    copying lazperf\PyLazperf.cpp -> build\lib.win-amd64-3.7\lazperf
    copying lazperf\PyLazperf.hpp -> build\lib.win-amd64-3.7\lazperf
    copying lazperf\PyLazperfTypes.hpp -> build\lib.win-amd64-3.7\lazperf
    copying lazperf\PyVlrCompressor.cpp -> build\lib.win-amd64-3.7\lazperf
    copying lazperf\lazperf.pxd -> build\lib.win-amd64-3.7\lazperf
    copying lazperf\pylazperfapi.pyx -> build\lib.win-amd64-3.7\lazperf
    running build_ext
    building 'lazperf.pylazperfapi' extension
    creating build\temp.win-amd64-3.7
    creating build\temp.win-amd64-3.7\Release
    creating build\temp.win-amd64-3.7\Release\lazperf
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MT -I.. "-Ic:\program files\python37\include" "-Ic:\program files\python37\include" -Ic:\users\user\appdata\local\temp\pip-req-build-1xp7tl_k\.eggs\numpy-1.17.1-py3.7-win-amd64.egg\numpy\core\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt" /EHsc /Tplazperf/pylazperfapi.cpp /Fobuild\temp.win-amd64-3.7\Release\lazperf/pylazperfapi.obj
    pylazperfapi.cpp
    c1xx: fatal error C1083: Cannot open source file: 'lazperf/pylazperfapi.cpp': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
```
I will test it with docker soon.

**Comment by hobu** [comment]
cython needs to make pylazperfapi.cpp. That should be happening in the setup.

**Comment by matthew-jones-uk** [comment]
Yup, looks good, would it be possible for you to push to pypi?

**Comment by hobu** [comment]
done.
